spring.application.name=zil-additional-service
server.port=${SERVER_PORT:8084}

main-service.base-url=${MAIN_SERVICE_BASE_URL:http://localhost:8083}

# LAB9 observability
observability.windows=10s,30s,1m
observability.tick-millis=5000
